### ISSUE TITLE
Inferring per-individual inbreeding coefficients between very distant species

### ISSUE THREAD

**Issue by Gongmian784** [Rosemeis/pcangsd#13]
Dear Rosemeis,

I got the GL file of 10 individuals, and each of them represents a species(the longest divergence time may be 4 million years). 
I want to estimate  per-individual inbreeding coefficients, but the inbreed method in PCAngsd is based on population structure and may take the divergence sites into account. As a result, I find the inbreeding coefficient of each sample is very high. 
I wonder is there any good way to calculate the per-individual inbreeding coefficient of samples splitting very long time(e.g. 4 million years)? I'd be really grateful if you could give me some suggestions.

Best
Mian

**Comment by Rosemeis** [comment]
Hi Mian,

For such a sample with so much differentiation, I would definitely use "-e 9", if it is not already inferred in the MAP test.
Then perhaps try to have a run with all three inbreed options and see how different the models work for this kind of dataset. And please report what you see. :smile: 

Best,
Jonas

**Comment by Rosemeis** [comment]
If the samples are as highly diverged as you explained, then you should use -e 9. Otherwise it would not be able to model all the genetic variation between the samples. However, it is worth noting that the sample size of 1 from each will make it very hard to model this variation! 

A negative inbreeding coefficient would mean that the individual has an excess of heterozygosity from what would be expected (compared to excess of homozygosity - inbreeding).

I'm gonna close this issue. Feel free to reopen if you run into any issues. :smile:

Best,
Jonas
