### ISSUE TITLE
NameError: global name 'rmse' is not defined

### ISSUE THREAD

**Issue by silvewheat** [Rosemeis/pcangsd#2]
Hello,
           When I use this new version to estimate inbreed by option -inbreed 1, an error occured like this:
![image](https://user-images.githubusercontent.com/19344997/34828857-e00d49c4-f719-11e7-9d22-81a14968245d.png)

Best !

**Comment by Rosemeis** [comment]
Hi.
Thank you very much for the feedback!

The bug has now been fixed and inbreeding estimations should be up and running. The entire inbreeding program will be upgraded in the near future for faster estimations. Right now I would recommend that you use the -inbreed 2 model, since -inbreed 1 tends to overestimate the inbreeding coefficients in low depth cases.
