### ISSUE TITLE
PCA performance with low depth and low sample size

### ISSUE THREAD

**Issue by nicolas931010** [Rosemeis/pcangsd#41]
Hi,

We have been running some simulations to test the performance of PCAngsd with varying sequencing depth and sample size. We simulated 9 populations on a 3 by 3 grid, created a 30Mbp chromosome, and simulated the low-coverage whole genome sequencing process with sequencing depth from 0.125x to 4x (per sample, shown in rows in the figures below) and sample size from 5 to 80 (per population, shown in columns in the figures below). We ran PCAngsd with the simulated data, and also tested the single read sampling method in ANGSD (`-doCov 1`). We found that at low sequencing depth and low sample size (top left corner of both figures below), ANGSD significantly outperforms PCAngsd, so we are wondering if this is something you would expect by the design of PCAngsd, or if we did something wrong when running it. And if it is the former, under what kind of scenario would you expect PCAngsd to outperform ANGSD? Please let me know if anything is unclear, or if you would like me to provide the code that we used or more details on our simulation. Thank you very much!

#### PCA with PCAngsd

![unnamed-chunk-5-1](https://user-images.githubusercontent.com/19261101/99036252-53974a00-254f-11eb-93fd-c78e270d65ec.png)

#### PCA with ANGSD `-doCov 1`

![unnamed-chunk-12-1](https://user-images.githubusercontent.com/19261101/99036205-3c585c80-254f-11eb-9af5-30e0d2f483b4.png)

Best,
Nicolas

**Comment by Rosemeis** [comment]
Hi Nicolas,

That is very interesting! In the simulations how many variants do you end up having on 30Mbp chromosomes? And did you tweak the "-e" parameter in PCAngsd yourself or let it try to infer it itself?

Best,
Jonas

**Comment by nicolas931010** [comment]
Hi Jonas,

Thank you very much for your reply! There are a total of ~3.8 million SNPs across all individuals in the simulation. Depending on the sequencing depth and sample size combination, ANGSD has called 57,856-229,055 SNPs with estimated allele frequency larger than 5%, which we then used these as input for PCAngsd. When running PCAngsd, we didn't tweak the "-e" parameter. Would you suggest us to try that?

Thanks,
Nicolas

**Comment by Rosemeis** [comment]
Okay. If you have simulated 9 "isolated" populations, then I would try "-e 8" in all scenarios. Otherwise a simple "-e 2" would be worth trying. The problem for PCAngsd is that is starts with a bad guess and iteratively tries to do it better from that. 

It would be cool if you could try that, and thanks for looking into this.

Best,
Jonas

**Comment by nicolas931010** [comment]
The populations that we've simulated are each connected to its neighbor by gene flow, so maybe "-e 2" would be more appropriate? But either way, we just tried both "-e 8" and "-e 2", and I am attaching the results below. As you can see, for certain sample size and sequencing depth combinations, this has improved the result, but overall, the performance is still not ideal in comparison with ANGSD. Please let me know what you think. Thank you very much!

#### PCAngsd with `-e 8`

![000005](https://user-images.githubusercontent.com/19261101/99126573-70299580-25d4-11eb-9c2d-a414fd395970.png)

#### PCAngsd with `-e 2`

![000004](https://user-images.githubusercontent.com/19261101/99126516-5425f400-25d4-11eb-8ac2-f7e62ffc6a7b.png)

Best,
Nicolas

**Comment by Rosemeis** [comment]
Yeah, I agree that "-e 2" is more appropriate. But it is very interesting results as we never pushed PCAngsd to its limits in this regard ourselves.
I think the problem here lies in that PCAngsd tries to deal with missingness by trying to model and impute it, while ANGSD "ignores" it, by simply only evaluating sites where both individuals have information when computing their pairwise distance. So when you have very few samples and very few sites, it has a hard time trying to infer the underlying global structure as it iteratively tries to impute all the missingness as well.
I imagine that when simulating a larger genome then it will perform much better.

But thank you for looking in to this! Let me know if you have any further questions. :-)

Best,
Jonas

**Comment by nicolas931010** [comment]
Thank you, Jonas! That makes sense.
